version = 1
SPDX-PackageName = "plane-telegram-webhooks"
SPDX-PackageSupplier = "CyberSport Masters <git@csmpro.ru>"
SPDX-PackageDownloadLocation = "https://git.csmpro.ru/csmpro/plane-telegram-webhooks"

[[annotations]]
path = [".forgejo/workflows/docker-image.yml", ".forgejo/workflows/release.yml", "package.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 CyberSport Masters <git@csmpro.ru>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [".gitignore", ".dockerignore", ".env.example", ".envrc", "docker-compose.yml", "nix/flake.lock", "yarn.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 CyberSport Masters <git@csmpro.ru>"
SPDX-License-Identifier = "MIT"
